---
 - name: Stop skynet application as a dm-vramiset user with Sudo privileges
   become: yes
   become_user: root
   command: /sbin/initctl stop skynet

 - name: Copy Rollback script to dev server with user wngapp
   become: yes
   become_user: wngapp
   copy:
     src: rollback_skynet.sh
     dest: /home/wngapp/rollback_skynet.sh
     mode: 0755


 - name: Execute Rollback script on dev server with user wngapp
   become: yes
   become_user: wngapp
   shell: sh /home/wngapp/rollback_skynet.sh
   chmod: 0755
   args:
     chdir: /home/wngapp/
   register: scriptoutput

 - debug: var=scriptoutput.stdout_lines

 - name: Start skynet application as a dm-vramiset user with Sudo privileges
   become: yes
   become_user: root
   command: /sbin/initctl start skynet
